### ISSUE TITLE
Ultra émouvant

### ISSUE THREAD

**Issue by mewzax** [Stanley-GF/PirateStealer-Explained#1]
Ça faisait longtemps j avais pas chialé comme ça

**Comment by mewzax** [comment]
Mais frérot t un sacré menteur tah l epoque tu m as dit tu te faisais plein de sous avec piratestealer

**Comment by NotPunchnox** [comment]
bah en vrai c'est juste un stealer beaucoup de gens en ont parlé c'est sur mais en réalité c'est du bas niveau

**Comment by mewzax** [comment]
> bah en vrai c'est juste un stealer beaucoup de gens en ont parlé c'est sur mais en réalité c'est du bas niveau

Qu'est ce que tu racontes le [bas niveau](https://code-garage.fr/blog/que-signifient-bas-niveau-et-haut-niveau-en-programmation/) c'est quand le langage ne fournit que peu d'abstraction par rapport au jeu d'instructions du processeur de la machine, tout le contraire du JavaScript avec lequel est écrit PirateStealer 🤓🤓🤓

**Comment by LeilaVanco** [comment]
Mewzax reviens là t'es parti où

**Comment by mewzax** [comment]
bahahah elle m'a retrouvé

**Comment by NotPunchnox** [comment]
@mewzax quand je disais bas niveau c'est son malware il est à chier et ça avait déjà été fait avant

**Comment by mewzax** [comment]
> @mewzax quand je disais bas niveau c'est son malware il est à chier et ça avait déjà été fait avant

Je sais je déconne

**Comment by Sascha-T** [comment]
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
